name: Build Development

on:
  push:
    branches: [ "development" ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
  pull_request:
    branches: [ "development" ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[Ci skip]')"
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build shadowJar

    - name: Upload Paper Jar Artifact
      uses: actions/upload-artifact@v4
      with:
        name: vortexia-core-paper-alpha-b.${{ github.run_number }}
        path: "vortexia-core-paper/build/libs/*.jar"
        retention-days: 14

    - name: Upload Velocity Jar Artifact
      uses: actions/upload-artifact@v4
      with:
        name: vortexia-core-velocity-alpha-b.${{ github.run_number }}
        path: "vortexia-core-velocity/build/libs/*.jar"
        retention-days: 14

    - name: Upload Bungee Jar Artifact
      uses: actions/upload-artifact@v4
      with:
        name: vortexia-core-bungee-alpha-b.${{ github.run_number }}
        path: "vortexia-core-bungee/build/libs/*.jar"
        retention-days: 14

    - name: Upload Sponge Jar Artifact
      uses: actions/upload-artifact@v4
      with:
        name: vortexia-core-sponge-alpha-b.${{ github.run_number }}
        path: "vortexia-core-sponge/build/libs/*.jar"
        retention-days: 14

    - name: Get Project Version
      id: get_version
      run: |
        chmod +x gradlew
        VERSION=$(./gradlew :vortexia-core-paper:properties -q | grep "^version:" | awk '{print $2}')
        echo "version=$VERSION" >> $GITHUB_OUTPUT

